### ISSUE TITLE
What are the benefits of doing this way than previous version?

### ISSUE THREAD

**Issue by schhunchha** [fatsu/ngx-destroy#2]

**Comment by fatsu** [comment]
With the decorator, it is your responsability to declare the property and decorate it. The decorator will internally remove the property definition and redefine it as `Observable<void>`. 

The typescript compiler uses the decorated property with the type you provided, not the one defined by the decorator. So, if you define it as `Observable<boolean>`, `Observable<string>`, or even `Subject<someClass>` that would pass, but be kind of awkward.

If you would want to use the decorated property in a service, you would have to pass it in yourself (or decorator a property on the service if service is used through the injector).

Using NgxDestroy$ as provider solves both these problems:
- the type is fixed: NgxDestroy$ (extends `Observable<void>`).
- it can easily be injected and/or re-provided in the injector tree

Hope this answers your question. Comments and remarks are appreciated!

**Comment by schhunchha** [comment]
my AOT build was failing, after I changed it to latest it works. have to provide it to each component though?

**Comment by fatsu** [comment]
Yes, you should provide it to each component that subscribes to (infinite) rxjs streams explicitly.
